name: tutor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  file_picker: ^6.1.1
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_ui_auth: ^1.13.0
  firebase_ui_oauth_google: 1.2.16
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.12
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  open_filex: ^4.4.0
  path_provider: ^2.1.2
  uuid: ^4.3.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
  - assets/
