swagger: "2.0"
info:
  version: "1.0.0"
  title: "Tutor"
  description: "API for AI-powered functionality in a language learning app"
securityDefinitions:
  key:
    type: apiKey
    in: header
    name: Authorization
security:
  - key: []
paths:
  /chat_messages:
    post:
      summary: Sends a message to the AI and receives a response.
      operationId: "SendChatMessage"
      description: This endpoint receives a user's message and returns the AI's response.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User message and additional information
          required: true
          schema:
            type: object
            properties:
              userId:
                type: string
                description: Unique identifier for the user.
              message:
                type: string
                description: The message text sent by the user.
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              reply:
                type: string
                description: AI's response to the user's message.
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/error"
        '401':
          description: unauthorized
          schema:
            $ref: "#/definitions/error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/error"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"

definitions:
  error:
    type: object
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  principal:
    type: "object"
    properties:
      email:
        type: "string"