swagger: "2.0"
info:
  version: "1.0.0"
  title: "Tutor"
  description: "API for AI-powered functionality in a language learning app"
securityDefinitions:
  key:
    type: apiKey
    in: header
    name: Authorization
security:
  - key: []
paths:
  /chat_messages:
    post:
      summary: Sends a text message to the AI and receives a response.
      operationId: "SendChatMessage"
      description: This endpoint receives a user's message and returns the AI's response.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User message and additional information
          required: true
          schema:
            type: object
            required:
              - text
              - timestamp
            properties:
              timestamp:
                type: integer
                format: int64
                description: The timestamp of the message.
              chatId:
                type: string
                description: The chat ID.
              text:
                type: string
                description: The message text sent by the user.
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              reply:
                type: string
                description: AI's response to the user's message.
              timestamp:
                type: integer
                format: int64
              chat:
                type: object
                $ref: '#/definitions/Chat'
                description: If the chatId is not provided in the request, the new chat will be created and this chat will be returned in the response.
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/error"
        '401':
          description: unauthorized
          schema:
            $ref: "#/definitions/error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/error"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /chats:
    get:
      description: "Get chats"
      operationId: "GetChats"
      produces:
        - application/json
      parameters:
        - in: query
          name: limit
          required: false
          type: integer
          format: int32
          default: 10
        - in: query
          name: timestamp
          description: timestamp starting from which chats are to be fetched
          required: false
          type: integer
          format: int64
          default: 0
      responses:
        200:
          description: A list of chats
          schema:
            type: object
            properties:
              chats:
                type: array
                items:
                  $ref: '#/definitions/Chat'
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/error"
        '401':
          description: unauthorized
          schema:
            $ref: "#/definitions/error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/error"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    post:
        summary: Creates a new chat.
        operationId: "CreateChat"
        description: This endpoint creates a new chat.
        consumes:
            - application/json
        produces:
            - application/json
        parameters:
          - in: body
            name: body
            description: Chat information
            required: true
            schema:
              type: object
              required:
              - typ
              - time
              properties:
                typ:
                  $ref: '#/definitions/ChatType'
                  x-go-name: ChatType
                time:
                  type: integer
                  format: int64
                  description: The timestamp of the chat.
        responses:
          '200':
            description: Successful response
            schema:
              type: object
              properties:
                chat:
                  type: object
                  $ref: '#/definitions/Chat'
                  description: The created chat.
          400:
            description: "Bad request"
            schema:
              $ref: "#/definitions/error"
          '401':
            description: unauthorized
            schema:
              $ref: "#/definitions/error"
          500:
            description: "Internal server error"
            schema:
              $ref: "#/definitions/error"
          default:
            description: error
            schema:
              $ref: "#/definitions/error"
  /chat_messages/{chatId}:
    get:
      description: "Get chat messages"
      operationId: "GetChatMessages"
      produces:
        - application/json
      parameters:
        - in: path
          name: chatId
          required: true
          type: string
        - in: query
          name: limit
          required: false
          type: integer
          format: int32
          default: 10
        - in: query
          name: timestamp
          description: timestamp starting from which messages are to be fetched
          required: false
          type: integer
          format: int64
          default: 0
      responses:
        200:
          description: A list of chat messages
          schema:
            type: object
            properties:
              messages:
                type: array
                items:
                  $ref: '#/definitions/ChatMessage'
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/error"
        '401':
          description: unauthorized
          schema:
            $ref: "#/definitions/error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/error"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /chat_voice_messages:
    post:
      summary: Sends an audio message to the AI and receives a response.
      operationId: "SendVoiceMessage"
      description: This endpoint receives a user's audio message and returns the AI's response.
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: formData
          name: file
          type: file
          description: The audio file to be sent.
          required: true
        - in: formData
          name: chatId
          type: string
          description: The chat ID.
          required: false
        - in: formData
          name: timestamp
          type: integer
          format: int64
          description: The timestamp of the message.
          required: true
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              usrTxt:
                type: string
                description: The user's message in text format.
              usrAudio:
                type: string
                description: Url to the user's audio message.
              usrTime:
                type: integer
                format: int64
                description: The timestamp of the user's message.
              replyTxt:
                type: string
                description: AI's text response to the user's message.
              replyAudio:
                type: string
                description: Url to the AI's audio response.
              replyTime:
                type: integer
                format: int64
                description: The timestamp of the AI's response.
              chat:
                type: object
                $ref: '#/definitions/Chat'
                description: If the chatId is not provided in the request, the new chat will be created and this chat will be returned in the response.
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/error"
        '401':
          description: unauthorized
          schema:
            $ref: "#/definitions/error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/error"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"

definitions:
  error:
    type: object
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  ChatMessage:
    type: object
    properties:
      userId:
        type: string
      text:
        type: string
      timestamp:
        type: integer
        format: int64
      curUsr:
        type: boolean
        x-go-name: IsFromCurrentUser
      audio:
        type: string
        x-go-name: AudioURL
  ChatType:
    type: integer
    format: int32
    enum:
      - 1
      - 2
      - 3
    x-enum-descriptions:
      - "General"
      - "Job Interview"
      - "Training specific questions from job interviews"
  Chat:
    type: object
    properties:
      chatId:
        type: string
      time:
        type: integer
        format: int64
      title:
        type: string
      typ:
        $ref: '#/definitions/ChatType'
      prep_msgs:
        type: array
        items:
          type: string
        x-go-name: PreparedMessages