// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteChatParams creates a new DeleteChatParams object
// no default values defined in spec.
func NewDeleteChatParams() DeleteChatParams {

	return DeleteChatParams{}
}

// DeleteChatParams contains all the bound params for the delete chat operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteChat
type DeleteChatParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	ChatID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteChatParams() beforehand.
func (o *DeleteChatParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rChatID, rhkChatID, _ := route.Params.GetOK("chatId")
	if err := o.bindChatID(rChatID, rhkChatID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChatID binds and validates parameter ChatID from path.
func (o *DeleteChatParams) bindChatID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ChatID = raw

	return nil
}
