// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/babadro/tutor/internal/models"
	"github.com/babadro/tutor/internal/models/swagger"
)

// DeleteChatHandlerFunc turns a function with the right signature into a delete chat handler
type DeleteChatHandlerFunc func(DeleteChatParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteChatHandlerFunc) Handle(params DeleteChatParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteChatHandler interface for that can handle valid delete chat params
type DeleteChatHandler interface {
	Handle(DeleteChatParams, *models.Principal) middleware.Responder
}

// NewDeleteChat creates a new http.Handler for the delete chat operation
func NewDeleteChat(ctx *middleware.Context, handler DeleteChatHandler) *DeleteChat {
	return &DeleteChat{Context: ctx, Handler: handler}
}

/*
DeleteChat swagger:route DELETE /chats deleteChat

Deletes a chat.

This endpoint deletes a chat.
*/
type DeleteChat struct {
	Context *middleware.Context
	Handler DeleteChatHandler
}

func (o *DeleteChat) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteChatParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteChatBody delete chat body
//
// swagger:model DeleteChatBody
type DeleteChatBody struct {

	// The chat ID.
	// Required: true
	ChatID *string `json:"chatId"`
}

// Validate validates this delete chat body
func (o *DeleteChatBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateChatID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteChatBody) validateChatID(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"chatId", "body", o.ChatID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete chat body based on context it is used
func (o *DeleteChatBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteChatBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteChatBody) UnmarshalBinary(b []byte) error {
	var res DeleteChatBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// DeleteChatOKBody delete chat o k body
//
// swagger:model DeleteChatOKBody
type DeleteChatOKBody struct {

	// The deleted chat.
	Chat *swagger.Chat `json:"chat,omitempty"`
}

// Validate validates this delete chat o k body
func (o *DeleteChatOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateChat(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteChatOKBody) validateChat(formats strfmt.Registry) error {
	if swag.IsZero(o.Chat) { // not required
		return nil
	}

	if o.Chat != nil {
		if err := o.Chat.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteChatOK" + "." + "chat")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this delete chat o k body based on the context it is used
func (o *DeleteChatOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateChat(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteChatOKBody) contextValidateChat(ctx context.Context, formats strfmt.Registry) error {

	if o.Chat != nil {
		if err := o.Chat.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteChatOK" + "." + "chat")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteChatOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteChatOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteChatOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
