// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/babadro/tutor/internal/models"
)

// DeleteChatHandlerFunc turns a function with the right signature into a delete chat handler
type DeleteChatHandlerFunc func(DeleteChatParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteChatHandlerFunc) Handle(params DeleteChatParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteChatHandler interface for that can handle valid delete chat params
type DeleteChatHandler interface {
	Handle(DeleteChatParams, *models.Principal) middleware.Responder
}

// NewDeleteChat creates a new http.Handler for the delete chat operation
func NewDeleteChat(ctx *middleware.Context, handler DeleteChatHandler) *DeleteChat {
	return &DeleteChat{Context: ctx, Handler: handler}
}

/*
DeleteChat swagger:route DELETE /chat/{chatId} deleteChat

Deletes a chat.

This endpoint deletes a chat.
*/
type DeleteChat struct {
	Context *middleware.Context
	Handler DeleteChatHandler
}

func (o *DeleteChat) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteChatParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
