// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/babadro/tutor/internal/models/swagger"
)

// DeleteChatOKCode is the HTTP code returned for type DeleteChatOK
const DeleteChatOKCode int = 200

/*
DeleteChatOK Successful response

swagger:response deleteChatOK
*/
type DeleteChatOK struct {

	/*
	  In: Body
	*/
	Payload *DeleteChatOKBody `json:"body,omitempty"`
}

// NewDeleteChatOK creates DeleteChatOK with default headers values
func NewDeleteChatOK() *DeleteChatOK {

	return &DeleteChatOK{}
}

// WithPayload adds the payload to the delete chat o k response
func (o *DeleteChatOK) WithPayload(payload *DeleteChatOKBody) *DeleteChatOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete chat o k response
func (o *DeleteChatOK) SetPayload(payload *DeleteChatOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteChatOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteChatBadRequestCode is the HTTP code returned for type DeleteChatBadRequest
const DeleteChatBadRequestCode int = 400

/*
DeleteChatBadRequest Bad request

swagger:response deleteChatBadRequest
*/
type DeleteChatBadRequest struct {

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewDeleteChatBadRequest creates DeleteChatBadRequest with default headers values
func NewDeleteChatBadRequest() *DeleteChatBadRequest {

	return &DeleteChatBadRequest{}
}

// WithPayload adds the payload to the delete chat bad request response
func (o *DeleteChatBadRequest) WithPayload(payload *swagger.Error) *DeleteChatBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete chat bad request response
func (o *DeleteChatBadRequest) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteChatBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteChatUnauthorizedCode is the HTTP code returned for type DeleteChatUnauthorized
const DeleteChatUnauthorizedCode int = 401

/*
DeleteChatUnauthorized unauthorized

swagger:response deleteChatUnauthorized
*/
type DeleteChatUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewDeleteChatUnauthorized creates DeleteChatUnauthorized with default headers values
func NewDeleteChatUnauthorized() *DeleteChatUnauthorized {

	return &DeleteChatUnauthorized{}
}

// WithPayload adds the payload to the delete chat unauthorized response
func (o *DeleteChatUnauthorized) WithPayload(payload *swagger.Error) *DeleteChatUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete chat unauthorized response
func (o *DeleteChatUnauthorized) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteChatUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteChatInternalServerErrorCode is the HTTP code returned for type DeleteChatInternalServerError
const DeleteChatInternalServerErrorCode int = 500

/*
DeleteChatInternalServerError Internal server error

swagger:response deleteChatInternalServerError
*/
type DeleteChatInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewDeleteChatInternalServerError creates DeleteChatInternalServerError with default headers values
func NewDeleteChatInternalServerError() *DeleteChatInternalServerError {

	return &DeleteChatInternalServerError{}
}

// WithPayload adds the payload to the delete chat internal server error response
func (o *DeleteChatInternalServerError) WithPayload(payload *swagger.Error) *DeleteChatInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete chat internal server error response
func (o *DeleteChatInternalServerError) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteChatInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
DeleteChatDefault error

swagger:response deleteChatDefault
*/
type DeleteChatDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewDeleteChatDefault creates DeleteChatDefault with default headers values
func NewDeleteChatDefault(code int) *DeleteChatDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteChatDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete chat default response
func (o *DeleteChatDefault) WithStatusCode(code int) *DeleteChatDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete chat default response
func (o *DeleteChatDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete chat default response
func (o *DeleteChatDefault) WithPayload(payload *swagger.Error) *DeleteChatDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete chat default response
func (o *DeleteChatDefault) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteChatDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
