// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetChatMessagesParams creates a new GetChatMessagesParams object
// with the default values initialized.
func NewGetChatMessagesParams() GetChatMessagesParams {

	var (
		// initialize parameters with default values

		limitDefault     = int32(10)
		timestampDefault = int64(0)
	)

	return GetChatMessagesParams{
		Limit: &limitDefault,

		Timestamp: &timestampDefault,
	}
}

// GetChatMessagesParams contains all the bound params for the get chat messages operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetChatMessages
type GetChatMessagesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	ChatID string
	/*
	  In: query
	  Default: 10
	*/
	Limit *int32
	/*timestamp starting from which messages are to be fetched
	  In: query
	  Default: 0
	*/
	Timestamp *int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetChatMessagesParams() beforehand.
func (o *GetChatMessagesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rChatID, rhkChatID, _ := route.Params.GetOK("chatId")
	if err := o.bindChatID(rChatID, rhkChatID, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	qTimestamp, qhkTimestamp, _ := qs.GetOK("timestamp")
	if err := o.bindTimestamp(qTimestamp, qhkTimestamp, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChatID binds and validates parameter ChatID from path.
func (o *GetChatMessagesParams) bindChatID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ChatID = raw

	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetChatMessagesParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetChatMessagesParams()
		return nil
	}

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "int32", raw)
	}
	o.Limit = &value

	return nil
}

// bindTimestamp binds and validates parameter Timestamp from query.
func (o *GetChatMessagesParams) bindTimestamp(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetChatMessagesParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("timestamp", "query", "int64", raw)
	}
	o.Timestamp = &value

	return nil
}
