// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/babadro/tutor/internal/models"
	"github.com/babadro/tutor/internal/models/swagger"
)

// GetChatMessagesHandlerFunc turns a function with the right signature into a get chat messages handler
type GetChatMessagesHandlerFunc func(GetChatMessagesParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetChatMessagesHandlerFunc) Handle(params GetChatMessagesParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetChatMessagesHandler interface for that can handle valid get chat messages params
type GetChatMessagesHandler interface {
	Handle(GetChatMessagesParams, *models.Principal) middleware.Responder
}

// NewGetChatMessages creates a new http.Handler for the get chat messages operation
func NewGetChatMessages(ctx *middleware.Context, handler GetChatMessagesHandler) *GetChatMessages {
	return &GetChatMessages{Context: ctx, Handler: handler}
}

/*
GetChatMessages swagger:route GET /chat_messages/{chatId} getChatMessages

Get chat messages
*/
type GetChatMessages struct {
	Context *middleware.Context
	Handler GetChatMessagesHandler
}

func (o *GetChatMessages) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetChatMessagesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetChatMessagesOKBody get chat messages o k body
//
// swagger:model GetChatMessagesOKBody
type GetChatMessagesOKBody struct {

	// messages
	Messages []*swagger.ChatMessage `json:"messages"`
}

// Validate validates this get chat messages o k body
func (o *GetChatMessagesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessages(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetChatMessagesOKBody) validateMessages(formats strfmt.Registry) error {
	if swag.IsZero(o.Messages) { // not required
		return nil
	}

	for i := 0; i < len(o.Messages); i++ {
		if swag.IsZero(o.Messages[i]) { // not required
			continue
		}

		if o.Messages[i] != nil {
			if err := o.Messages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getChatMessagesOK" + "." + "messages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get chat messages o k body based on the context it is used
func (o *GetChatMessagesOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateMessages(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetChatMessagesOKBody) contextValidateMessages(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Messages); i++ {

		if o.Messages[i] != nil {
			if err := o.Messages[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getChatMessagesOK" + "." + "messages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetChatMessagesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetChatMessagesOKBody) UnmarshalBinary(b []byte) error {
	var res GetChatMessagesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
