// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/babadro/tutor/internal/models/swagger"
)

// SendVoiceMessageOKCode is the HTTP code returned for type SendVoiceMessageOK
const SendVoiceMessageOKCode int = 200

/*
SendVoiceMessageOK Successful response

swagger:response sendVoiceMessageOK
*/
type SendVoiceMessageOK struct {

	/*
	  In: Body
	*/
	Payload *SendVoiceMessageOKBody `json:"body,omitempty"`
}

// NewSendVoiceMessageOK creates SendVoiceMessageOK with default headers values
func NewSendVoiceMessageOK() *SendVoiceMessageOK {

	return &SendVoiceMessageOK{}
}

// WithPayload adds the payload to the send voice message o k response
func (o *SendVoiceMessageOK) WithPayload(payload *SendVoiceMessageOKBody) *SendVoiceMessageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the send voice message o k response
func (o *SendVoiceMessageOK) SetPayload(payload *SendVoiceMessageOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SendVoiceMessageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SendVoiceMessageBadRequestCode is the HTTP code returned for type SendVoiceMessageBadRequest
const SendVoiceMessageBadRequestCode int = 400

/*
SendVoiceMessageBadRequest Bad request

swagger:response sendVoiceMessageBadRequest
*/
type SendVoiceMessageBadRequest struct {

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewSendVoiceMessageBadRequest creates SendVoiceMessageBadRequest with default headers values
func NewSendVoiceMessageBadRequest() *SendVoiceMessageBadRequest {

	return &SendVoiceMessageBadRequest{}
}

// WithPayload adds the payload to the send voice message bad request response
func (o *SendVoiceMessageBadRequest) WithPayload(payload *swagger.Error) *SendVoiceMessageBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the send voice message bad request response
func (o *SendVoiceMessageBadRequest) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SendVoiceMessageBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SendVoiceMessageUnauthorizedCode is the HTTP code returned for type SendVoiceMessageUnauthorized
const SendVoiceMessageUnauthorizedCode int = 401

/*
SendVoiceMessageUnauthorized unauthorized

swagger:response sendVoiceMessageUnauthorized
*/
type SendVoiceMessageUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewSendVoiceMessageUnauthorized creates SendVoiceMessageUnauthorized with default headers values
func NewSendVoiceMessageUnauthorized() *SendVoiceMessageUnauthorized {

	return &SendVoiceMessageUnauthorized{}
}

// WithPayload adds the payload to the send voice message unauthorized response
func (o *SendVoiceMessageUnauthorized) WithPayload(payload *swagger.Error) *SendVoiceMessageUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the send voice message unauthorized response
func (o *SendVoiceMessageUnauthorized) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SendVoiceMessageUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SendVoiceMessageInternalServerErrorCode is the HTTP code returned for type SendVoiceMessageInternalServerError
const SendVoiceMessageInternalServerErrorCode int = 500

/*
SendVoiceMessageInternalServerError Internal server error

swagger:response sendVoiceMessageInternalServerError
*/
type SendVoiceMessageInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewSendVoiceMessageInternalServerError creates SendVoiceMessageInternalServerError with default headers values
func NewSendVoiceMessageInternalServerError() *SendVoiceMessageInternalServerError {

	return &SendVoiceMessageInternalServerError{}
}

// WithPayload adds the payload to the send voice message internal server error response
func (o *SendVoiceMessageInternalServerError) WithPayload(payload *swagger.Error) *SendVoiceMessageInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the send voice message internal server error response
func (o *SendVoiceMessageInternalServerError) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SendVoiceMessageInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
SendVoiceMessageDefault error

swagger:response sendVoiceMessageDefault
*/
type SendVoiceMessageDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *swagger.Error `json:"body,omitempty"`
}

// NewSendVoiceMessageDefault creates SendVoiceMessageDefault with default headers values
func NewSendVoiceMessageDefault(code int) *SendVoiceMessageDefault {
	if code <= 0 {
		code = 500
	}

	return &SendVoiceMessageDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the send voice message default response
func (o *SendVoiceMessageDefault) WithStatusCode(code int) *SendVoiceMessageDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the send voice message default response
func (o *SendVoiceMessageDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the send voice message default response
func (o *SendVoiceMessageDefault) WithPayload(payload *swagger.Error) *SendVoiceMessageDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the send voice message default response
func (o *SendVoiceMessageDefault) SetPayload(payload *swagger.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SendVoiceMessageDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
