// Code generated by go-swagger; DO NOT EDIT.

package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ChatType chat type
//
// swagger:model ChatType
type ChatType int32

// for schema
var chatTypeEnum []interface{}

func init() {
	var res []ChatType
	if err := json.Unmarshal([]byte(`[1,2]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		chatTypeEnum = append(chatTypeEnum, v)
	}
}

func (m ChatType) validateChatTypeEnum(path, location string, value ChatType) error {
	if err := validate.EnumCase(path, location, value, chatTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this chat type
func (m ChatType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateChatTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this chat type based on context it is used
func (m ChatType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
