// Code generated by go-swagger; DO NOT EDIT.

package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChatMessage chat message
//
// swagger:model ChatMessage
type ChatMessage struct {

	// is from current user
	IsFromCurrentUser bool `json:"curUsr,omitempty"`

	// text
	Text string `json:"text,omitempty"`

	// timestamp
	Timestamp int64 `json:"timestamp,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`
}

// Validate validates this chat message
func (m *ChatMessage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this chat message based on context it is used
func (m *ChatMessage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChatMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChatMessage) UnmarshalBinary(b []byte) error {
	var res ChatMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
