// Code generated by go-swagger; DO NOT EDIT.

package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// VoiceMessageType voice message type
//
// swagger:model VoiceMessageType
type VoiceMessageType int32

// for schema
var voiceMessageTypeEnum []interface{}

func init() {
	var res []VoiceMessageType
	if err := json.Unmarshal([]byte(`[1]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		voiceMessageTypeEnum = append(voiceMessageTypeEnum, v)
	}
}

func (m VoiceMessageType) validateVoiceMessageTypeEnum(path, location string, value VoiceMessageType) error {
	if err := validate.EnumCase(path, location, value, voiceMessageTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this voice message type
func (m VoiceMessageType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateVoiceMessageTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this voice message type based on context it is used
func (m VoiceMessageType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
