package main

var interviewQuestionsWithoutVariations = []string{
	"Erzählen Sie mir von Zeiten, in denen Sie ein großes Gefühl der Erfüllung oder des Erfolgs verspürten.",
	"Erzählen Sie mir von Zeiten, in denen Sie etwas repariert haben, das nicht funktioniert hat.",
	"Erzählen Sie mir von einer Zeit, in der Sie eine schwierige Entscheidung treffen mussten.",
	"Erzählen Sie mir von einer Zeit, in der Sie einen Führer oder ein Team beeinflussen mussten.",
	"Erzählen Sie mir von Zeiten, in denen Sie von etwas überrascht wurden oder etwas übersehen haben.",
}

var oldQuesions = []string{
	"Können Sie mir kurz von einigen Projekten erzählen, an denen Sie gearbeitet haben, und wie Sie diese von Anfang bis Ende umgesetzt haben?",
	"Stellen Sie sich vor, ich bin ein Technik-Laie. Können Sie mir in einfachen Worten erklären, was Sie tun?",
	"Haben Sie schon einmal eine Präsentation gehalten?",
	"Wie gut sind Ihre SQL-Kenntnisse?",
	"Wer ist Ihr Vorbild in der Welt der Technik?",
	"Nennen Sie eine Website oder App, die Sie nervt. Was stört Sie daran?",
	"Was sind Ihre größten Schwächen?",
	"Was sind Ihre größten Stärken?",
	"Erzählen Sie mir von einer Situation, in der ein Kollege Ihre Arbeit vor anderen kritisiert hat. Wie haben Sie reagiert? Wie hat dieses Ereignis Ihre Kommunikation mit anderen beeinflusst?",
	"Wie stellen Sie sicher, dass jemand versteht, was Sie sagen?",
	"Erzählen Sie mir von einer Zeit, als Sie komplexe Informationen präsentieren mussten.",
	"Erzählen Sie mir von einer Zeit, als Sie Ihre schriftlichen Kommunikationsfähigkeiten einsetzen mussten, um einen wichtigen Punkt zu vermitteln.",
	"Erzählen Sie mir von einer Zeit, als Sie eine Frist nicht eingehalten haben. \nWas haben Sie versäumt? Was waren die Konsequenzen? Was haben Sie daraus gelernt?",
	"Erzählen Sie mir von einer Zeit, als Sie besonders effektiv bei der Priorisierung von Aufgaben waren und ein Projekt termingerecht abgeschlossen haben.",
	"Beschreiben Sie eine Situation, in der Sie viele Projekte gleichzeitig erledigen mussten. Welche Schritte haben Sie unternommen, um sie alle zu erledigen?",
	"Wie setzen Sie Prioritäten bei der Planung Ihrer Zeit? Geben Sie mir ein Beispiel.",
	"Geben Sie mir ein Beispiel für eine Zeit, in der Sie eine schwierige Entscheidung treffen mussten.",
	"Beschreiben Sie ein spezifisches Problem, das Sie für Ihren Arbeitgeber gelöst haben. Wie sind Sie das Problem angegangen? Welche Rolle spielten andere? Was war das Ergebnis?",
	"Geben Sie mir ein Beispiel, bei dem es sich ausgezahlt hat, sich Zeit für eine Entscheidung zu nehmen.",
	"Erzählen Sie uns von der größten Veränderung, mit der Sie in Ihrer vorherigen Beschäftigung konfrontiert waren. Wie sind Sie damit umgegangen?",
	"Beschreiben Sie eine Zeit, in der Sie etwas Komplexes einem Kollegen erklären mussten. Auf welche Probleme sind Sie gestoßen und wie haben Sie sie gelöst?",
	"Erzählen Sie uns von einer Zeit, in der Sie einen unkonventionellen Ansatz zur Lösung eines Problems entwickelt haben. Wie haben Sie diesen neuen Ansatz entwickelt? Welche Herausforderungen sind Ihnen begegnet und wie haben Sie sie bewältigt?",
	"Erzählen Sie uns von einer Entscheidung, die Sie getroffen haben, von der Sie wussten, dass sie bei bestimmten Personen unpopulär sein würde. Wie haben Sie den Entscheidungsprozess gehandhabt? Wie sind Sie mit den negativen Reaktionen anderer umgegangen?",
	"Beschreiben Sie eine Situation, in der Sie mitten in einem Projekt Ihren Ansatz geändert haben. Was hat Sie dazu veranlasst, Ihren Ansatz zu ändern? Wie haben Sie diese Änderung reibungslos umgesetzt?",
	"Beschreiben Sie eine Situation, in der Sie gebeten wurden, eine Aufgabe zu erfüllen, die Sie noch nie zuvor durchgeführt hatten.",
	"Erzählen Sie uns von einer Zeit, als Sie jemand bat, etwas zu tun, dem Sie widersprachen. Wie haben Sie die Situation gehandhabt?",
	"Beschreiben Sie eine Zeit, in der Sie die Leistung eines Teams verbessern mussten. Welche Herausforderungen sind Ihnen begegnet und wie haben Sie sie bewältigt?",
	"Beschreiben Sie eine Zeit, in der Sie negatives Feedback von einem Arbeitgeber, Kollegen oder Kunden erhalten haben. Was war das Ergebnis?",
	"Beschreiben Sie eine Zeit, in der Sie Mitglied eines Teams waren. Wie haben Sie positiv zum Team beigetragen?",
	"Sind Sie der Typ, der während seines Urlaubs E-Mails überprüft?",
	"Ist diese Position eine ähnliche Rolle wie andere Jobs, die Sie in Betracht ziehen?",
	"Wenn Sie für ein beliebiges Unternehmen arbeiten könnten, wo würden Sie arbeiten?",
	"Warum möchten Sie hier arbeiten?",
	"Wo sehen Sie sich in fünf Jahren?",
	"Was denken Sie, werden Ihre Referenzen über Sie sagen?",
	"Welcher Teil der Stellenbeschreibung klingt am herausforderndsten und warum?",
	"Warum sollte ich Sie einstellen?",
	"Warum möchten Sie für dieses Unternehmen arbeiten?",
	"Was für eine Person sind Sie? Erzählen Sie mir von sich.",
	"Was sind Ihre Hauptstärken (Fähigkeiten, Fertigkeiten, Persönlichkeitsmerkmale)?",
}
