// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"mime/multipart"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewSendVoiceMessageParams creates a new SendVoiceMessageParams object
// no default values defined in spec.
func NewSendVoiceMessageParams() SendVoiceMessageParams {

	return SendVoiceMessageParams{}
}

// SendVoiceMessageParams contains all the bound params for the send voice message operation
// typically these are obtained from a http.Request
//
// swagger:parameters SendVoiceMessage
type SendVoiceMessageParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The voice message file from the user.
	  Required: true
	  In: formData
	*/
	VoiceMessage io.ReadCloser
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSendVoiceMessageParams() beforehand.
func (o *SendVoiceMessageParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}

	voiceMessage, voiceMessageHeader, err := r.FormFile("voiceMessage")
	if err != nil {
		res = append(res, errors.New(400, "reading file %q failed: %v", "voiceMessage", err))
	} else if err := o.bindVoiceMessage(voiceMessage, voiceMessageHeader); err != nil {
		// Required: true
		res = append(res, err)
	} else {
		o.VoiceMessage = &runtime.File{Data: voiceMessage, Header: voiceMessageHeader}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindVoiceMessage binds file parameter VoiceMessage.
//
// The only supported validations on files are MinLength and MaxLength
func (o *SendVoiceMessageParams) bindVoiceMessage(file multipart.File, header *multipart.FileHeader) error {
	return nil
}
