// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/babadro/tutor/internal/models"
)

// SendVoiceMessageHandlerFunc turns a function with the right signature into a send voice message handler
type SendVoiceMessageHandlerFunc func(SendVoiceMessageParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SendVoiceMessageHandlerFunc) Handle(params SendVoiceMessageParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SendVoiceMessageHandler interface for that can handle valid send voice message params
type SendVoiceMessageHandler interface {
	Handle(SendVoiceMessageParams, *models.Principal) middleware.Responder
}

// NewSendVoiceMessage creates a new http.Handler for the send voice message operation
func NewSendVoiceMessage(ctx *middleware.Context, handler SendVoiceMessageHandler) *SendVoiceMessage {
	return &SendVoiceMessage{Context: ctx, Handler: handler}
}

/*
SendVoiceMessage swagger:route POST /voice_messages sendVoiceMessage

Processes a voice message and returns a response.
*/
type SendVoiceMessage struct {
	Context *middleware.Context
	Handler SendVoiceMessageHandler
}

func (o *SendVoiceMessage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSendVoiceMessageParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// SendVoiceMessageOKBody send voice message o k body
//
// swagger:model SendVoiceMessageOKBody
type SendVoiceMessageOKBody struct {

	// Transcription of the input voice message.
	VoiceMessageTranscript string `json:"voiceMessageTranscript,omitempty"`

	// URL of the voice message input file.
	VoiceMessageURL string `json:"voiceMessageUrl,omitempty"`

	// Text transcription of the voice response.
	VoiceResponseTranscript string `json:"voiceResponseTranscript,omitempty"`

	// URL to the voice response file.
	VoiceResponseURL string `json:"voiceResponseUrl,omitempty"`
}

// Validate validates this send voice message o k body
func (o *SendVoiceMessageOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this send voice message o k body based on context it is used
func (o *SendVoiceMessageOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SendVoiceMessageOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SendVoiceMessageOKBody) UnmarshalBinary(b []byte) error {
	var res SendVoiceMessageOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
