// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfneJPqWTUJPFRQIBaruLFb3zQllc_L70',
    appId: '1:10752760457:web:03beb4cc6d4843875f8458',
    messagingSenderId: '10752760457',
    projectId: 'tutor-d920d',
    authDomain: 'tutor-d920d.firebaseapp.com',
    storageBucket: 'tutor-d920d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXPN9AsLxd-PT-UFy0zcQs9zYWSdaxZkI',
    appId: '1:10752760457:android:ebe6022fea1ad5055f8458',
    messagingSenderId: '10752760457',
    projectId: 'tutor-d920d',
    storageBucket: 'tutor-d920d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6CPTfMM_J3_r8UAqWmjGGQjPnsZG1j00',
    appId: '1:10752760457:ios:76a61d41ff5557f85f8458',
    messagingSenderId: '10752760457',
    projectId: 'tutor-d920d',
    storageBucket: 'tutor-d920d.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6CPTfMM_J3_r8UAqWmjGGQjPnsZG1j00',
    appId: '1:10752760457:ios:4d5517ab0da1611b5f8458',
    messagingSenderId: '10752760457',
    projectId: 'tutor-d920d',
    storageBucket: 'tutor-d920d.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
