// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Tutor
//
//	API for AI-powered functionality in a language learning app
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
